run:
  timeout: 5m
  tests: false
linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - exhaustruct
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - unconvert
    - unparam
    - unused
    - whitespace